### ISSUE TITLE
No file found with name "users.csv"

### ISSUE THREAD

**Issue by NilmarShereef** [PrinceS25/Grand-Truthers#1]
As per the readme.txt file, there is no "users.csv" file in Data folder. When I rename "users_dict.csv" file into "users.csv", it will solve the first error while running  "**python3 preprocess.py** " and will throw the next error which is :

```
raise ValueError("Usecols do not match names.")
ValueError: Usecols do not match names.
```
Error is throwing from the line  below and I think panda package si not getting th proper file (userws.csv).

return pd.read_csv(filepath, index_col=index, usecols=cols)

Any Fix?

**Comment by Prince25** [comment]
Sorry for the mixup. The data folder was supposed to be ignored by Git but we probably added that constraint too late in the process. I updated the README.txt and added instructions on how to acquire the sample data files. It should work for you now. Let me know of your outcome.

**Comment by NilmarShereef** [comment]
Yes, I got a work around condition with the newly provided data set. Also did small changes in code (Skipped `sort=False` argument from panda calls), Which may be the version issue. Anyway, it worked well. Thank you for quick clearance and help.
